CREATE TABLE USER(
      IDX INT PRIMARY KEY
    , ID VARCHAR2(255)
    , PASSWD VARCHAR(255)
    , NAME VARCHAR2(255)
    , LOGIN_TYPE VARCHAR2(255)
    );

ALTER TABLE USER 
  ADD CONSTRAINT USER_UNIQUE UNIQUE(ID, LOGIN_TYPE);

CREATE SEQUENCE USER_SEQ;

CREATE TABLE AUTHORITIES(
      IDX INT PRIMARY KEY
    , USER_IDX INT
    , AUTH VARCHAR2(255)
    );
CREATE SEQUENCE AUTHORITIES_SEQ;

CREATE SEQUENCE USER_SEQ;

CREATE TABLE VIDEO(
      IDX INT PRIMARY KEY
    , OWNER_IDX INT
    , VIDEO_ID VARCHAR2(255)
    );
CREATE SEQUENCE VIDEO_SEQ;

CREATE TABLE VIDEO_STOCK(
      IDX INT PRIMARY KEY
    , VIDEO_IDX INT
    , STOCK_SIZE NUMBER
    , PRICE_PER_NUMBER NUMBER
    );
CREATE SEQUENCE VIDEO_STOCK_SEQ;

CREATE TABLE STOCK(
      IDX INT PRIMARY KEY
    , VIDEO_IDX INT
    , OWNER_IDX INT
    , SIZE NUMBER
    , PRICE NUMBER
    );
CREATE SEQUENCE STOCK_SEQ;